Only run one index create / update concurrently
ssb-ngi-pointer/jitdb pull request #96
Opened 2021-01-23 20:31 UTC by arj03

Converting ssb-about to use jitdb revealed that jitdb doesn't handle concurrent index creates very well. Meaning it will just run as many in parallel as you give it ;) This PR remedies so that only one is running and just calls the waiting after it has finished. Massively faster. There is one caveat this PR handles the simple case of multiple `and(vote())`. But doesn't handle two concurrent requst like `and(author(), isPublic())` and `and(author())`. I don't think this will be a big problem in real life and I value the simplicity of this approach.

Not exactly sure how to write a good test for this. I testing this manually by doing two queries concurrently and with the PR you results in half the time.

2021-01-23 21:11 UTC, staltz commented
Will review on Monday

2021-01-25 10:16 UTC, staltz commented
@arj03 I understood this to be "Only run one log scan at a time, for indexing", right?

I tried adding this benchmark, to see if it would capture the performance boost:

```js
test('query a huge index twice concurrently', (t) => {
  db.onReady(() => {
    const done = multicb({ pluck: 1 })
    const start = Date.now()

    query(
      fromDB(db),
      and(equal(seekType, 'post', { indexType: 'type' })),
      toCallback(done())
    )

    query(
      fromDB(db),
      and(equal(seekType, 'post', { indexType: 'type' })),
      toCallback(done())
    )

    done((err) => {
      if (err) t.fail(err)
      const duration = Date.now() - start
      t.pass(`duration: ${duration}ms`)
      fs.appendFileSync(
        reportPath,
        `| Query 1 big index twice concurrently | ${duration}ms |\n`
      )
      t.end()
    })
  })
})
```

Does this accurately reflect what you meant? It doesn't seem to run faster with the PR. A single of these queries is roughly `224ms`, and then running them concurrently is `466ms` with or without this PR.

I have some comments about the code (some possible corner case bugs), but first I'd like to prove on my computer that this gives performance benefits.

2021-01-25 10:23 UTC, arj03 commented
Strange, are you sure that is creating the indexes? 200ms sounds very low, so it seems more like it is just doing 2 queries on an existing index. But yeah that is a good idea to test it that way. Will give it a try.

2021-01-25 10:24 UTC, staltz commented
Aaah, so yeah the indexes are not being *created*, because this is the 3rd run of the query. The 1st run created the index. Will adapt it, just a second.

2021-01-25 10:28 UTC, staltz commented
Before PR: `379ms`
After PR: `264ms`

2021-01-25 10:43 UTC, staltz requested changes

2021-01-25 10:43 UTC, staltz commented on index.js
> +  const waitingIndexUpdate = {}
`Map` is more suitable (also for performance) if you're adding and `delete`ing frequently

2021-01-25 10:43 UTC, staltz commented on index.js
> +    const waitingKey = opsMissingIndexes.join()
I think this should be `opsMissingIndexes.map(op => op.data.indexName).join()`, right? Otherwise we get `[Object],[Object]` strings

2021-01-25 10:56 UTC, staltz commented on index.js
> +    const waitingKey = opsMissingIndexes.join()
and maybe with a separator, like `join('|')` to make sure we don't do `value_content_x` + `value_content_y` = `value_content_xvalue_content_y`

2021-01-25 11:02 UTC, arj03 commented
Thanks for the review. Really good points. Will push up a fix in a minute, I found that there were some missing index names in the prefix test ;-)

2021-01-25 11:06 UTC, arj03 commented
Sorry for the git confusion. Should be there now.

2021-01-25 11:14 UTC, staltz requested changes

2021-01-25 11:14 UTC, staltz commented on index.js
> +    if (waitingIndexUpdate[waitingKey]) {
```js
if (waitingIndexUpdate.has(waitingKey)) {
  waitingIndexUpdate.get(waitingKey).push(cb)
  return // wait for other index update
} else waitingIndexUpdate.set(waitingKey, [])
```

2021-01-25 11:14 UTC, staltz commented on index.js
> +        delete waitingIndexUpdate[waitingKey]
```js
waitingIndexUpdate.get(waitingKey).forEach((cb) => cb())
waitingIndexUpdate.delete(waitingKey)
```

More about Maps here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

2021-01-25 11:17 UTC, arj03 commented on index.js
> +    if (waitingIndexUpdate[waitingKey]) {
Right :facepalm:

2021-01-25 11:31 UTC, staltz approved these changes

2021-01-25 11:32 UTC, staltz commented
Thanks for working out the nitpicks :)

2021-01-25 11:34 UTC, arj03 commented
Thanks for your patience :)

2021-01-25 11:34 UTC, merged